export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


export const GET_ADVERTISEMENTS_START = 'GET_ADVERTISEMENTS_START';
export const GET_ADVERTISEMENTS_SUCCESS = 'GET_ADVERTISEMENTS_SUCCESS';
export const GET_ADVERTISEMENTS_FAIL = 'GET_ADVERTISEMENTS_FAIL';
